MIRAVEIL_ISLAND_HALL_MapScripts::
	.byte 0

MIRAVEIL_BANQUET_1F_EventScript_Lady1::
	msgbox MIRAVEIL_BANQUET_1F_Text_Lady1, MSGBOX_NPC
	end

MIRAVEIL_BANQUET_1F_EventScript_Lady2::
	msgbox MIRAVEIL_BANQUET_1F_Text_Lady2, MSGBOX_NPC
	end

MIRAVEIL_BANQUET_1F_EventScript_Captain::
	msgbox MIRAVEIL_BANQUET_1F_Text_Captain, MSGBOX_NPC
	end

MIRAVEIL_BANQUET_1F_EventScript_Gentleman::
	msgbox MIRAVEIL_BANQUET_1F_Text_Gentleman, MSGBOX_NPC
	end

MIRAVEIL_BANQUET_1F_EventScript_Man::
	msgbox MIRAVEIL_BANQUET_1F_Text_Man, MSGBOX_NPC
	end

MIRAVEIL_BANQUET_1F_EventScript_Kid::
	msgbox MIRAVEIL_BANQUET_1F_Text_Kid, MSGBOX_NPC
	end

MIRAVEIL_BANQUET_1F_Text_Lady1:
	.string "The hors d'oeuvres this year are\n"
	.string "simply divine. You wouldn't\l"
	.string "understand.$"

MIRAVEIL_BANQUET_1F_Text_Lady2:
	.string "Oh, don't mind me. I'm only here\n"
	.string "to be seen.$"

MIRAVEIL_BANQUET_1F_Text_Captain:
	.string "I sailed these waters forty years.\n"
	.string "Now I ferry rich folk to parties.\p"
	.string "…The pay's better. I won't pretend\n"
	.string "otherwise.$"

MIRAVEIL_BANQUET_1F_Text_Gentleman:
	.string "Brigham funds all of this, you know.\n"
	.string "Marvelous man. Never asks a thing\l"
	.string "of us in return.\p"
	.string "Whatever he gets up to is his own\n"
	.string "business.$"

MIRAVEIL_BANQUET_1F_Text_Man:
	.string "You're not on the guest list, are\n"
	.string "you? I can always tell.$"

MIRAVEIL_BANQUET_1F_Text_Kid:
	.string "Mother says I'm not allowed upstairs\n"
	.string "during the grown-ups' party.\p"
	.string "It's boring down here.$"