ENPALE_ROUTE_2_MapScripts::
	.byte 0

ENPALE_ROUTE_2_EventScript_Twins::
	trainerbattle_double TRAINER_ROUTE_2_TWINS, ENPALE_ROUTE_2_Text_TwinsIntro, ENPALE_ROUTE_2_Text_TwinsDefeat, ENPALE_ROUTE_2_Text_TwinsNotEnough
	msgbox ENPALE_ROUTE_2_Text_TwinsRepeat, MSGBOX_AUTOCLOSE
	end

ENPALE_ROUTE_2_EventScript_Jordan::
	trainerbattle_single TRAINER_ROUTE_2_JORDAN, ENPALE_ROUTE_2_Text_JordanIntro, ENPALE_ROUTE_2_Text_JordanDefeat
	msgbox ENPALE_ROUTE_2_Text_JordanRepeat, MSGBOX_AUTOCLOSE
	end

ENPALE_ROUTE_2_EventScript_Lisa::
	trainerbattle_single TRAINER_ROUTE_2_LISA, ENPALE_ROUTE_2_Text_LisaIntro, ENPALE_ROUTE_2_Text_LisaDefeat
	msgbox ENPALE_ROUTE_2_Text_LisaRepeat, MSGBOX_AUTOCLOSE
	end

ENPALE_ROUTE_2_EventScript_Ben::
	trainerbattle_single TRAINER_ROUTE_2_BEN, ENPALE_ROUTE_2_Text_BenIntro, ENPALE_ROUTE_2_Text_BenDefeat
	msgbox ENPALE_ROUTE_2_Text_BenRepeat, MSGBOX_AUTOCLOSE
	end

ENPALE_ROUTE_2_EventScript_Joe::
	trainerbattle_single TRAINER_ROUTE_2_JOE, ENPALE_ROUTE_2_Text_JoeIntro, ENPALE_ROUTE_2_Text_JoeDefeat
	msgbox ENPALE_ROUTE_2_Text_JoeRepeat, MSGBOX_AUTOCLOSE
	end

ENPALE_ROUTE_2_Text_TwinsIntro:
	.string "Come play with us!\nDouble battles are fun!$"

ENPALE_ROUTE_2_Text_TwinsDefeat:
	.string "You're mean!$"

ENPALE_ROUTE_2_Text_TwinsRepeat:
	.string "Double battles are the best!$"

ENPALE_ROUTE_2_Text_TwinsNotEnough:
	.string "You need two Pokemon\nfor a double battle!$"

ENPALE_ROUTE_2_Text_JordanIntro:
	.string "Hey, don't distract me\nwhile I'm fishing!$"

ENPALE_ROUTE_2_Text_JordanDefeat:
	.string "Alright, alright!$"

ENPALE_ROUTE_2_Text_JordanRepeat:
	.string "Just let me focus\non my fishing!$"

ENPALE_ROUTE_2_Text_LisaIntro:
	.string "What a beautiful day!$"

ENPALE_ROUTE_2_Text_LisaDefeat:
	.string "Oh well.$"

ENPALE_ROUTE_2_Text_LisaRepeat:
	.string "Better out here\nthan in a cave.$"

ENPALE_ROUTE_2_Text_BenIntro:
	.string "I'm training before\nRidley Cave!$"

ENPALE_ROUTE_2_Text_BenDefeat:
	.string "I guess I'm not ready.$"

ENPALE_ROUTE_2_Text_BenRepeat:
	.string "You should train up before\ngoing in the cave.$"

ENPALE_ROUTE_2_Text_JoeIntro:
	.string "I'm not afraid of caves!\nI'm just not ready to go\lin yet!$"

ENPALE_ROUTE_2_Text_JoeDefeat:
	.string "Aw shucks!$"

ENPALE_ROUTE_2_Text_JoeRepeat:
	.string "I'll go in right after you!$"

ENPALE_ROUTE_2_EventScript_Sign::
	msgbox ENPALE_ROUTE_2_Text_Sign, MSGBOX_SIGN
	end

ENPALE_ROUTE_2_Text_Sign:
	.string "Route 2\nRidley Bridge to Coppergate City {DOWN_ARROW}$"

EnpaleRoute2_EventScript_Barney::
	trainerbattle_single TRAINER_BARNEY_R2, EnpaleRoute2_Text_BarneyIntro, EnpaleRoute2_Text_BarneyDefeat
	msgbox EnpaleRoute2_Text_BarneyPost, MSGBOX_AUTOCLOSE
	end

EnpaleRoute2_EventScript_Julia::
	trainerbattle_single TRAINER_JULIA_R2, EnpaleRoute2_Text_JuliaIntro, EnpaleRoute2_Text_JuliaDefeat
	msgbox EnpaleRoute2_Text_JuliaPost, MSGBOX_AUTOCLOSE
	end

EnpaleRoute2_EventScript_Carl::
	trainerbattle_single TRAINER_CARL_R2, EnpaleRoute2_Text_CarlIntro, EnpaleRoute2_Text_CarlDefeat
	msgbox EnpaleRoute2_Text_CarlPost, MSGBOX_AUTOCLOSE
	end

EnpaleRoute2_EventScript_Mike::
	trainerbattle_single TRAINER_MIKE_R2, EnpaleRoute2_Text_MikeIntro, EnpaleRoute2_Text_MikeDefeat
	msgbox EnpaleRoute2_Text_MikePost, MSGBOX_AUTOCLOSE
	end

EnpaleRoute2_EventScript_Kirk::
	trainerbattle_single TRAINER_KIRK_R2, EnpaleRoute2_Text_KirkIntro, EnpaleRoute2_Text_KirkDefeat
	msgbox EnpaleRoute2_Text_KirkPost, MSGBOX_AUTOCLOSE
	end

EnpaleRoute2_Text_BarneyIntro:
	.string "Flying Pokémon are the best!$"
EnpaleRoute2_Text_BarneyDefeat:
	.string "I'll never be like Robin!$"
EnpaleRoute2_Text_BarneyPost:
	.string "Soar high!$"

EnpaleRoute2_Text_JuliaIntro:
	.string "Look at my cute Pokémon!$"
EnpaleRoute2_Text_JuliaDefeat:
	.string "My babies!$"
EnpaleRoute2_Text_JuliaPost:
	.string "You're rude!$"

EnpaleRoute2_Text_CarlIntro:
	.string "I LOVE POKEMON!$"
EnpaleRoute2_Text_CarlDefeat:
	.string "I think I got a little excited there…$"
EnpaleRoute2_Text_CarlPost:
	.string "Safe travels!$"

EnpaleRoute2_Text_MikeIntro:
	.string "You should try breeding!$"
EnpaleRoute2_Text_MikeDefeat:
	.string "I guess I should've raised them first!$"
EnpaleRoute2_Text_MikePost:
	.string "Baby Pokémon are cute, but they're not\nvery strong.$"

EnpaleRoute2_Text_KirkIntro:
	.string "I was born to raise hell!$"
EnpaleRoute2_Text_KirkDefeat:
	.string "Overkill!$"
EnpaleRoute2_Text_KirkPost:
	.string "Stay clean!$"