#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H
#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(REST) \
    F(THIEF) \
    F(IRON_HEAD) \
    F(SKILL_SWAP) \
    F(OVERHEAT) \
    F(BULLDOZE) \
    F(DUAL_WINGBEAT) \
    F(AQUA_JET) \
    F(POWER_UP_PUNCH) \
    F(ACROBATICS) \
    F(GRASS_KNOT) \
    F(FLASH_CANNON) \
    F(TRICK_ROOM) \
    F(DARK_PULSE) \
    F(DAZZLING_GLEAM) \
    F(SUBSTITUTE) \
    F(POWER_GEM) \
    F(SCALD) \
    F(WILL_O_WISP) \
    F(HEX) \
    F(DRAIN_PUNCH) \
    F(FOUL_PLAY) \
    F(FOCUS_BLAST) \
    F(DRAGON_PULSE) \
    F(ENERGY_BALL) \
    F(U_TURN) \
    F(VOLT_SWITCH) \
    F(SHADOW_CLAW) \
    F(X_SCISSOR) \
    F(STONE_EDGE) \
    F(POISON_JAB) \
    F(AVALANCHE) \
    F(SWORDS_DANCE) \
    F(INFESTATION) \
    F(SLEEP_TALK) \
    F(ROCK_SLIDE) \
    F(FIRE_FANG) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(FLAME_CHARGE) \
    F(STORED_POWER) \
    F(BODY_SLAM) \
    F(FIRE_PUNCH) \
    F(THUNDER_PUNCH) \
    F(ICE_PUNCH) \
    F(ELECTRO_BALL) \
    F(ROCK_BLAST) \
    F(BODY_PRESS) \
    F(SPIKES) \
    F(STEALTH_ROCK) \
    F(TOXIC_SPIKES) \
    F(LEECH_LIFE) \
    F(DRILL_RUN) \
    F(TRICK) \
    F(LIQUIDATION) \
    F(NASTY_PLOT) \
    F(PHANTOM_FORCE) \
    F(OUTRAGE)
#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)
#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)
#endif