gText_Birch_Welcome::
        .string "Are you ready? Don't tell me\n"
        .string "you forgot...\p"
        .string "It's me! Brutus! Your father!\p"
        .string "Today's the day you have your\n"
        .string "first Pokémon battle!\p"
        .string "$"
gText_Birch_Pokemon::
        .string "As you know, Pokémon are powerful\n"
        .string "creatures capable of unbelievable\l"
        .string "strength!\p"
        .string "\n"
        .string "$"
gText_Birch_MainSpeech::
        .string "And as Pokémon Trainers, it's our\n"
        .string "job to tame and train them!\p"
        .string "Being the Pokémon Champion of\n"
        .string "Enpale, and now you...\p"
        .string "$"
gText_Birch_AndYouAre::
        .string "And you are?$"
gText_Birch_BoyOrGirl::
        .string "Are you a boy?\n"
        .string "Or are you a girl?$"
gText_Birch_WhatsYourName::
        .string "All right.\n"
        .string "What's your name?$"
gText_Birch_SoItsPlayer::
        .string "So it's {PLAYER}{KUN}?$"
gText_Birch_YourePlayer::
        .string "Ah, okay!\p"
        .string "$"
gText_Birch_AreYouReady::
        .string "You will have the honor of\n"
        .string "battling in my place against\l"
        .string "my very own rival, Umbra!\p"
        .string "Come on, and prove yourself\n"
        .string "worthy of being the heir to\l"
        .string "the throne of the Pokémon world!\p"
        .string "$"