//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/region_map/region_map_sections.json and Inja template src/data/region_map/region_map_sections.json.txt
//

#ifndef GUARD_DATA_REGION_MAP_REGION_MAP_ENTRIES_H
#define GUARD_DATA_REGION_MAP_REGION_MAP_ENTRIES_H

const struct RegionMapLocation gRegionMapEntries[] = {
    [MAPSEC_LITTLEROOT_TOWN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("LITTLEROOT TOWN"),
    },
    [MAPSEC_OLDALE_TOWN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Baynoe Town"),
    },
    [MAPSEC_DEWFORD_TOWN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Rosebank Town"),
    },
    [MAPSEC_LAVARIDGE_TOWN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Valerytown"),
    },
    [MAPSEC_FALLARBOR_TOWN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Quarren Town"),
    },
    [MAPSEC_VERDANTURF_TOWN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("VERDANTURF TOWN"),
    },
    [MAPSEC_PACIFIDLOG_TOWN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("PACIFIDLOG TOWN"),
    },
    [MAPSEC_PETALBURG_CITY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("PETALBURG CITY"),
    },
    [MAPSEC_SLATEPORT_CITY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("SLATEPORT CITY"),
    },
    [MAPSEC_MAUVILLE_CITY] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("Coppergate City"),
    },
    [MAPSEC_RUSTBORO_CITY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("Minsi City"),
    },
    [MAPSEC_FORTREE_CITY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("FORTREE CITY"),
    },
    [MAPSEC_LILYCOVE_CITY] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("Miraveil Island"),
    },
    [MAPSEC_MOSSDEEP_CITY] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("MOSSDEEP CITY"),
    },
    [MAPSEC_SOOTOPOLIS_CITY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SOOTOPOLIS CITY"),
    },
    [MAPSEC_EVER_GRANDE_CITY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("Veldtmoor City"),
    },
    [MAPSEC_ROUTE_101] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 101"),
    },
    [MAPSEC_ROUTE_102] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 102"),
    },
    [MAPSEC_ROUTE_103] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 103"),
    },
    [MAPSEC_ROUTE_104] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 104"),
    },
    [MAPSEC_ROUTE_105] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 105"),
    },
    [MAPSEC_ROUTE_106] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 106"),
    },
    [MAPSEC_ROUTE_107] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 107"),
    },
    [MAPSEC_ROUTE_108] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 108"),
    },
    [MAPSEC_ROUTE_109] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 109"),
    },
    [MAPSEC_ROUTE_110] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 110"),
    },
    [MAPSEC_ROUTE_111] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 6,
        .name = COMPOUND_STRING("ROUTE 111"),
    },
    [MAPSEC_ROUTE_112] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 112"),
    },
    [MAPSEC_ROUTE_113] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 113"),
    },
    [MAPSEC_ROUTE_114] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 114"),
    },
    [MAPSEC_ROUTE_115] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 115"),
    },
    [MAPSEC_ROUTE_116] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 116"),
    },
    [MAPSEC_ROUTE_117] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 117"),
    },
    [MAPSEC_ROUTE_118] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 118"),
    },
    [MAPSEC_ROUTE_119] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 6,
        .name = COMPOUND_STRING("ROUTE 119"),
    },
    [MAPSEC_ROUTE_120] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 4,
        .name = COMPOUND_STRING("ROUTE 120"),
    },
    [MAPSEC_ROUTE_121] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 121"),
    },
    [MAPSEC_ROUTE_122] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("ROUTE 122"),
    },
    [MAPSEC_ROUTE_123] = {
        .x = 0,
        .y = 0,
        .width = 5,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 123"),
    },
    [MAPSEC_ROUTE_124] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 124"),
    },
    [MAPSEC_ROUTE_125] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 2,
        .name = COMPOUND_STRING("ROUTE 125"),
    },
    [MAPSEC_ROUTE_126] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 126"),
    },
    [MAPSEC_ROUTE_127] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 3,
        .name = COMPOUND_STRING("ROUTE 127"),
    },
    [MAPSEC_ROUTE_128] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 128"),
    },
    [MAPSEC_ROUTE_129] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 129"),
    },
    [MAPSEC_ROUTE_130] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 130"),
    },
    [MAPSEC_ROUTE_131] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 131"),
    },
    [MAPSEC_ROUTE_132] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 132"),
    },
    [MAPSEC_ROUTE_133] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 133"),
    },
    [MAPSEC_ROUTE_134] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 134"),
    },
    [MAPSEC_UNDERWATER_124] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 3,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_UNDERWATER_126] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 3,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_UNDERWATER_127] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 3,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_UNDERWATER_128] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_UNDERWATER_SOOTOPOLIS] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_GRANITE_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("GRANITE CAVE"),
    },
    [MAPSEC_MT_CHIMNEY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Ridley Cave"),
    },
    [MAPSEC_SAFARI_ZONE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SAFARI ZONE"),
    },
    [MAPSEC_BATTLE_FRONTIER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("BATTLE FRONTIER"),
    },
    [MAPSEC_PETALBURG_WOODS] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("PETALBURG WOODS"),
    },
    [MAPSEC_RUSTURF_TUNNEL] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("RUSTURF TUNNEL"),
    },
    [MAPSEC_ABANDONED_SHIP] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Kinneret Town"),
    },
    [MAPSEC_NEW_MAUVILLE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("NEW MAUVILLE"),
    },
    [MAPSEC_METEOR_FALLS] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("METEOR FALLS"),
    },
    [MAPSEC_METEOR_FALLS2] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("METEOR FALLS"),
    },
    [MAPSEC_MT_PYRE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("MT. PYRE"),
    },
    [MAPSEC_AQUA_HIDEOUT_OLD] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("{AQUA} HIDEOUT"),
    },
    [MAPSEC_SHOAL_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SHOAL CAVE"),
    },
    [MAPSEC_SEAFLOOR_CAVERN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SEAFLOOR CAVERN"),
    },
    [MAPSEC_UNDERWATER_SEAFLOOR_CAVERN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_VICTORY_ROAD] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("VICTORY ROAD"),
    },
    [MAPSEC_MIRAGE_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Grant Island"),
    },
    [MAPSEC_CAVE_OF_ORIGIN] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Whitecaps"),
    },
    [MAPSEC_SOUTHERN_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SOUTHERN ISLAND"),
    },
    [MAPSEC_FIERY_PATH] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("FIERY PATH"),
    },
    [MAPSEC_FIERY_PATH2] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("FIERY PATH"),
    },
    [MAPSEC_JAGGED_PASS] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("JAGGED PASS"),
    },
    [MAPSEC_JAGGED_PASS2] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("JAGGED PASS"),
    },
    [MAPSEC_SEALED_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SEALED CHAMBER"),
    },
    [MAPSEC_UNDERWATER_SEALED_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_SCORCHED_SLAB] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SCORCHED SLAB"),
    },
    [MAPSEC_ISLAND_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ISLAND CAVE"),
    },
    [MAPSEC_DESERT_RUINS] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("DESERT RUINS"),
    },
    [MAPSEC_ANCIENT_TOMB] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ANCIENT TOMB"),
    },
    [MAPSEC_INSIDE_OF_TRUCK] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("INSIDE OF TRUCK"),
    },
    [MAPSEC_SKY_PILLAR] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SKY PILLAR"),
    },
    [MAPSEC_SECRET_BASE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SECRET BASE"),
    },
    [MAPSEC_DYNAMIC] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = (const u8[])_(""),
    },
    [MAPSEC_PALLET_TOWN] = {
        .x = 9,
        .y = 7,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Kinneret Town"),
    },
    [MAPSEC_VIRIDIAN_CITY] = {
        .x = 12,
        .y = 12,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Valerytown"),
    },
    [MAPSEC_PEWTER_CITY] = {
        .x = 2,
        .y = 6,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Quarren Town"),
    },
    [MAPSEC_CERULEAN_CITY] = {
        .x = 9,
        .y = 1,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Veldtmoor City"),
    },
    [MAPSEC_LAVENDER_TOWN] = {
        .x = 4,
        .y = 8,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Coppergate City"),
    },
    [MAPSEC_VERMILION_CITY] = {
        .x = 5,
        .y = 1,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Lenox Town"),
    },
    [MAPSEC_CELADON_CITY] = {
        .x = 8,
        .y = 9,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Delmark City"),
    },
    [MAPSEC_FUCHSIA_CITY] = {
        .x = 17,
        .y = 8,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Rosebank Town"),
    },
    [MAPSEC_CINNABAR_ISLAND] = {
        .x = 22,
        .y = 3,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Miraveil Island"),
    },
    [MAPSEC_INDIGO_PLATEAU] = {
        .x = 13,
        .y = 4,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Baynoe Town"),
    },
    [MAPSEC_SAFFRON_CITY] = {
        .x = 8,
        .y = 4,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Minsi City"),
    },
    [MAPSEC_ROUTE_4_POKECENTER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 4"),
    },
    [MAPSEC_ROUTE_10_POKECENTER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 10"),
    },
    [MAPSEC_ROUTE_1] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("Route 1"),
    },
    [MAPSEC_ROUTE_2] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("Route 2"),
    },
    [MAPSEC_ROUTE_3] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("Route 3"),
    },
    [MAPSEC_ROUTE_4] = {
        .x = 0,
        .y = 0,
        .width = 6,
        .height = 1,
        .name = COMPOUND_STRING("Route 4"),
    },
    [MAPSEC_ROUTE_5] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("Route 5"),
    },
    [MAPSEC_ROUTE_6] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("Route 6"),
    },
    [MAPSEC_ROUTE_7] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("Route 7"),
    },
    [MAPSEC_ROUTE_8] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("Route 8"),
    },
    [MAPSEC_ROUTE_9] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("Route 9"),
    },
    [MAPSEC_ROUTE_10] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("Route 10"),
    },
    [MAPSEC_ROUTE_11] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("Route 11"),
    },
    [MAPSEC_ROUTE_12] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 5,
        .name = COMPOUND_STRING("Route 12"),
    },
    [MAPSEC_ROUTE_13] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("Route 13"),
    },
    [MAPSEC_ROUTE_14] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("Route 14"),
    },
    [MAPSEC_ROUTE_15] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("Route 15"),
    },
    [MAPSEC_ROUTE_16] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("Route 16"),
    },
    [MAPSEC_ROUTE_17] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 5,
        .name = COMPOUND_STRING("Route 17"),
    },
    [MAPSEC_ROUTE_18] = {
        .x = 0,
        .y = 0,
        .width = 5,
        .height = 1,
        .name = COMPOUND_STRING("Route 18"),
    },
    [MAPSEC_ROUTE_19] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("Route 19"),
    },
    [MAPSEC_ROUTE_20] = {
        .x = 0,
        .y = 0,
        .width = 7,
        .height = 1,
        .name = COMPOUND_STRING("Route  20"),
    },
    [MAPSEC_ROUTE_21] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("ROUTE 21"),
    },
    [MAPSEC_ROUTE_22] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 22"),
    },
    [MAPSEC_ROUTE_23] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 4,
        .name = COMPOUND_STRING("ROUTE 23"),
    },
    [MAPSEC_ROUTE_24] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("ROUTE 24"),
    },
    [MAPSEC_ROUTE_25] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("ROUTE 25"),
    },
    [MAPSEC_VIRIDIAN_FOREST] = {
        .x = 9,
        .y = 6,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Allenwood Forest"),
    },
    [MAPSEC_MT_MOON] = {
        .x = 2,
        .y = 5,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Lehigh Tunnel"),
    },
    [MAPSEC_S_S_ANNE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("S.S. ANNE"),
    },
    [MAPSEC_UNDERGROUND_PATH] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("UNDERGROUND PATH"),
    },
    [MAPSEC_UNDERGROUND_PATH_2] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("UNDERGROUND PATH"),
    },
    [MAPSEC_DIGLETTS_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("DIGLETT'S CAVE"),
    },
    [MAPSEC_KANTO_VICTORY_ROAD] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("VICTORY ROAD"),
    },
    [MAPSEC_ROCKET_HIDEOUT] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ROCKET HIDEOUT"),
    },
    [MAPSEC_SILPH_CO] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SILPH CO."),
    },
    [MAPSEC_POKEMON_MANSION] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("POKéMON MANSION"),
    },
    [MAPSEC_KANTO_SAFARI_ZONE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SAFARI ZONE"),
    },
    [MAPSEC_POKEMON_LEAGUE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("POKéMON LEAGUE"),
    },
    [MAPSEC_ROCK_TUNNEL] = {
        .x = 13,
        .y = 3,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Bergen Hill"),
    },
    [MAPSEC_SEAFOAM_ISLANDS] = {
        .x = 19,
        .y = 6,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Grant Island"),
    },
    [MAPSEC_POKEMON_TOWER] = {
        .x = 15,
        .y = 10,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Wallar Marshlands"),
    },
    [MAPSEC_CERULEAN_CAVE] = {
        .x = 3,
        .y = 3,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Whitecaps"),
    },
    [MAPSEC_POWER_PLANT] = {
        .x = 5,
        .y = 6,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Ridley Cave"),
    },
    [MAPSEC_ONE_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Rosebank Town"),
    },
    [MAPSEC_TWO_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Baynoe Town"),
    },
    [MAPSEC_THREE_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("THREE ISLAND"),
    },
    [MAPSEC_FOUR_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("FOUR ISLAND"),
    },
    [MAPSEC_FIVE_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("FIVE ISLAND"),
    },
    [MAPSEC_SEVEN_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SEVEN ISLAND"),
    },
    [MAPSEC_SIX_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SIX ISLAND"),
    },
    [MAPSEC_KINDLE_ROAD] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 6,
        .name = COMPOUND_STRING("KINDLE ROAD"),
    },
    [MAPSEC_TREASURE_BEACH] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("TREASURE BEACH"),
    },
    [MAPSEC_CAPE_BRINK] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("CAPE BRINK"),
    },
    [MAPSEC_BOND_BRIDGE] = {
        .x = 0,
        .y = 0,
        .width = 4,
        .height = 1,
        .name = COMPOUND_STRING("BOND BRIDGE"),
    },
    [MAPSEC_THREE_ISLE_PORT] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("THREE ISLE PORT"),
    },
    [MAPSEC_RESORT_GORGEOUS] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("RESORT GORGEOUS"),
    },
    [MAPSEC_WATER_LABYRINTH] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("WATER LABYRINTH"),
    },
    [MAPSEC_FIVE_ISLE_MEADOW] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("FIVE ISLE MEADOW"),
    },
    [MAPSEC_MEMORIAL_PILLAR] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("MEMORIAL PILLAR"),
    },
    [MAPSEC_OUTCAST_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("OUTCAST ISLAND"),
    },
    [MAPSEC_GREEN_PATH] = {
        .x = 0,
        .y = 0,
        .width = 3,
        .height = 1,
        .name = COMPOUND_STRING("GREEN PATH"),
    },
    [MAPSEC_WATER_PATH] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 5,
        .name = COMPOUND_STRING("WATER PATH"),
    },
    [MAPSEC_RUIN_VALLEY] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 2,
        .name = COMPOUND_STRING("RUIN VALLEY"),
    },
    [MAPSEC_TRAINER_TOWER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 2,
        .name = COMPOUND_STRING("TRAINER TOWER"),
    },
    [MAPSEC_CANYON_ENTRANCE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("CANYON ENTRANCE"),
    },
    [MAPSEC_SEVAULT_CANYON] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("SEVAULT CANYON"),
    },
    [MAPSEC_TANOBY_RUINS] = {
        .x = 0,
        .y = 0,
        .width = 7,
        .height = 1,
        .name = COMPOUND_STRING("TANOBY RUINS"),
    },
    [MAPSEC_SEVII_ISLE_22] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("SEVII ISLE 22"),
    },
    [MAPSEC_SEVII_ISLE_23] = {
        .x = 0,
        .y = 0,
        .width = 6,
        .height = 1,
        .name = COMPOUND_STRING("SEVII ISLE 23"),
    },
    [MAPSEC_SEVII_ISLE_24] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("SEVII ISLE 24"),
    },
    [MAPSEC_NAVEL_ROCK_FRLG] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("NAVEL ROCK"),
    },
    [MAPSEC_MT_EMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("MT. EMBER"),
    },
    [MAPSEC_BERRY_FOREST] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Wallar Marshlands"),
    },
    [MAPSEC_ICEFALL_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ICEFALL CAVE"),
    },
    [MAPSEC_ROCKET_WAREHOUSE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ROCKET WAREHOUSE"),
    },
    [MAPSEC_TRAINER_TOWER_2] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("TRAINER TOWER"),
    },
    [MAPSEC_DOTTED_HOLE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("DOTTED HOLE"),
    },
    [MAPSEC_LOST_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("LOST CAVE"),
    },
    [MAPSEC_PATTERN_BUSH] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("PATTERN BUSH"),
    },
    [MAPSEC_ALTERING_CAVE_FRLG] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ALTERING CAVE"),
    },
    [MAPSEC_TANOBY_CHAMBERS] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("TANOBY CHAMBERS"),
    },
    [MAPSEC_THREE_ISLE_PATH] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("THREE ISLE PATH"),
    },
    [MAPSEC_TANOBY_KEY] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("TANOBY KEY"),
    },
    [MAPSEC_BIRTH_ISLAND_FRLG] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("BIRTH ISLAND"),
    },
    [MAPSEC_MONEAN_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("MONEAN CHAMBER"),
    },
    [MAPSEC_LIPTOO_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("LIPTOO CHAMBER"),
    },
    [MAPSEC_WEEPTH_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("WEEPTH CHAMBER"),
    },
    [MAPSEC_DILFORD_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("DILFORD CHAMBER"),
    },
    [MAPSEC_SCUFIB_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SCUFIB CHAMBER"),
    },
    [MAPSEC_RIXY_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("RIXY CHAMBER"),
    },
    [MAPSEC_VIAPOIS_CHAMBER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("VIAPOIS CHAMBER"),
    },
    [MAPSEC_EMBER_SPA] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("EMBER SPA"),
    },
    [MAPSEC_SPECIAL_AREA] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("SPECIAL AREA"),
    },
    [MAPSEC_AQUA_HIDEOUT] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("AQUA HIDEOUT"),
    },
    [MAPSEC_MAGMA_HIDEOUT] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("MAGMA HIDEOUT"),
    },
    [MAPSEC_MIRAGE_TOWER] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("MIRAGE TOWER"),
    },
    [MAPSEC_BIRTH_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("Bergen Hill"),
    },
    [MAPSEC_FARAWAY_ISLAND] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("FARAWAY ISLAND"),
    },
    [MAPSEC_ARTISAN_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ARTISAN CAVE"),
    },
    [MAPSEC_MARINE_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("MARINE CAVE"),
    },
    [MAPSEC_UNDERWATER_MARINE_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_TERRA_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("TERRA CAVE"),
    },
    [MAPSEC_UNDERWATER_105] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 3,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_UNDERWATER_125] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 2,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_UNDERWATER_129] = {
        .x = 0,
        .y = 0,
        .width = 2,
        .height = 1,
        .name = COMPOUND_STRING("UNDERWATER"),
    },
    [MAPSEC_DESERT_UNDERPASS] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("DESERT UNDERPASS"),
    },
    [MAPSEC_ALTERING_CAVE] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("ALTERING CAVE"),
    },
    [MAPSEC_NAVEL_ROCK] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("NAVEL ROCK"),
    },
    [MAPSEC_TRAINER_HILL] = {
        .x = 0,
        .y = 0,
        .width = 1,
        .height = 1,
        .name = COMPOUND_STRING("TRAINER HILL"),
    },
};

#endif // GUARD_DATA_REGION_MAP_REGION_MAP_ENTRIES_H
